# All valid intents the chatbot can recognize
ALLOWED_INTENTS = [
    "BOOK_APPOINTMENT",
    "CHECK_DOCTOR_AVAILABILITY",
    "CANCEL_APPOINTMENT",
    "RESCHEDULE_APPOINTMENT",
    "VIEW_REPORT",
    "VIEW_PRESCRIPTION",
    "VIEW_BILLS",
    "PAY_BILL",
    "SYMPTOM_ANALYSIS",
    "GENERAL_MEDICAL_QUERY",
]